name: Deploy AWS Lambda .NET

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Restore dependencies
        run: dotnet restore ./AwsAppFileSystem/AwsAppFileSystem.csproj

      - name: Build project
        run: dotnet build ./AwsAppFileSystem/AwsAppFileSystem.csproj --configuration Release

  
